export const categories = [
    [
        {
            "detail_id": "48269",
            "iep_id": "259",
            "goal_id": "22420",
            "parent_id": "22419",
            "goal_type": "B",
            "service_group": "Academics",
            "service_type": "Academics : Literacy",
            "iep_goal": "By mid-year, given modeling, direct instruction, review and reteach methods daily, and multi-sensory teaching strategies, Valentino will point to or touch pictures in a book to convey literal meaning in all settings with 75% accuracy in 3 out of 4 consecutive trials with moderate (6-8 tactile cues) support measured by data collection.",
            "goal_sequence": null,
            "comment_id": "10",
            "goal_comments": "Valentino demonstrates slow and steady progress towards this benchmark. He has demonstrated an average of 56% accuracy toward the goal criteria. Valentino is currently able to point to and touch pictures in a book with hand-over-hand support. He is also able to answer questions about the book in order convey the literal meaning of the contents of the story. For the upcoming quarter, Valentino will work on joint attention and hand-over-hand support in order to improve his consistency and accuracy with moderate verbal cues.",
            "level_of_performance": "3",
            "goal_done": "true",
            "is_active": 1,
            "iep_is_active": "1",
            "detail_mod_by": null,
            "detail_mod_date": null
        },
        {
            "detail_id": "48270",
            "iep_id": "259",
            "goal_id": "22421",
            "parent_id": "22419",
            "goal_type": "B",
            "service_group": "Academics",
            "service_type": "Academics : Literacy",
            "iep_goal": "In one year, given modeling, direct instruction, review and reteach methods daily, and multi-sensory teaching strategies, Valentino will point to or touch pictures in a book to convey literal meaning in all settings with 75% accuracy in 3 out of 4 consecutive trials with minimal (1-5 tactile cues) support measured by data collection.",
            "goal_sequence": null,
            "comment_id": "6",
            "goal_comments": "NI",
            "level_of_performance": "NI",
            "goal_done": "true",
            "is_active": 1,
            "iep_is_active": "1",
            "detail_mod_by": null,
            "detail_mod_date": null
        },
        {
            "detail_id": 0,
            "iep_id": "259",
            "goal_id": "22419",
            "parent_id": "0",
            "goal_type": "G",
            "service_group": "Academics",
            "service_type": "Academics : Literacy",
            "iep_goal": "In one year, given modeling, direct instruction, review and reteach methods daily, and multi-sensory teaching strategies, Valentino will point to or touch pictures in a book to convey literal meaning in all settings with 75% accuracy in 3 out of 4 consecutive trials with minimal (1-5 tactile cues) support measured by data collection.",
            "goal_sequence": null,
            "comment_id": "0",
            "goal_comments": "",
            "level_of_performance": "",
            "iep_is_active": "1",
            "goal_done": "true"
        }
    ],
    [
        {
            "detail_id": "48265",
            "iep_id": "259",
            "goal_id": "22416",
            "parent_id": "22415",
            "goal_type": "B",
            "service_group": "Academics",
            "service_type": "Academics : Math",
            "iep_goal": "By mid-year, when given counting manipulative (objects, visuals) and number cards, Valentino will identify numbers up to 1 to demonstrate one-to-one correspondence in all settings with 75% accuracy in 3 out of 4 consecutive trials with moderate  (6-8 cues) support measured by data collection.",
            "goal_sequence": null,
            "comment_id": "9",
            "goal_comments": "Limited opportunities to address this benchmark this quarter. In the upcoming quarter, Valentino will work on pointing to and numbering manipulatives using his device with moderate verbal cues.",
            "level_of_performance": "1",
            "goal_done": "true",
            "is_active": 1,
            "iep_is_active": "1",
            "detail_mod_by": null,
            "detail_mod_date": null
        },
        {
            "detail_id": "48266",
            "iep_id": "259",
            "goal_id": "22417",
            "parent_id": "22415",
            "goal_type": "B",
            "service_group": "Academics",
            "service_type": "Academics : Math",
            "iep_goal": "By mid-year, when given counting manipulative (objects, visuals) and number cards, Valentino will identify numbers up to 1 to demonstrate one-to-one correspondence in all settings with 75% accuracy in 3 out of 4 consecutive trials with minimal  (1-5 cues) support measured by data collection.",
            "goal_sequence": null,
            "comment_id": "6",
            "goal_comments": "NI",
            "level_of_performance": "NI",
            "goal_done": "true",
            "is_active": 1,
            "iep_is_active": "1",
            "detail_mod_by": null,
            "detail_mod_date": null
        },
        {
            "detail_id": "48267",
            "iep_id": "259",
            "goal_id": "22418",
            "parent_id": "22415",
            "goal_type": "B",
            "service_group": "Academics",
            "service_type": "Academics : Math",
            "iep_goal": "In one year, when given counting manipulative (objects, visuals) and number cards, Valentino will identify numbers up to 2 to demonstrate one-to-one correspondence in all settings with 75% accuracy in 3 out of 4 consecutive trials with moderate  (6-8 cues) support measured by data collection.",
            "goal_sequence": null,
            "comment_id": "6",
            "goal_comments": "NI",
            "level_of_performance": "NI",
            "goal_done": "true",
            "is_active": 1,
            "iep_is_active": "1",
            "detail_mod_by": null,
            "detail_mod_date": null
        },
        {
            "detail_id": "48284",
            "iep_id": "259",
            "goal_id": "23350",
            "parent_id": "22415",
            "goal_type": "B",
            "service_group": "Academics",
            "service_type": "Academics : Math",
            "iep_goal": "In one year, when given counting manipulative (objects, visuals) and number cards, Valentino will identify numbers up to 2 to demonstrate one-to-one correspondence in all settings with 75% accuracy in 3 out of 4 consecutive trials with minimal  (1-5 cues) support measured by data collection.",
            "goal_sequence": null,
            "comment_id": "6",
            "goal_comments": "NI",
            "level_of_performance": "NI",
            "goal_done": "true",
            "is_active": 1,
            "iep_is_active": "1",
            "detail_mod_by": null,
            "detail_mod_date": null
        },
        {
            "detail_id": 0,
            "iep_id": "259",
            "goal_id": "22415",
            "parent_id": "0",
            "goal_type": "G",
            "service_group": "Academics",
            "service_type": "Academics : Math",
            "iep_goal": "In one year, when given counting manipulative (objects, visuals) and number cards, Valentino will identify numbers up to 2 to demonstrate one-to-one correspondence in all settings with 75% accuracy in 3 out of 4 consecutive trials with minimal  (1-5  cues) support measured by data collection.",
            "goal_sequence": null,
            "comment_id": "0",
            "goal_comments": "",
            "level_of_performance": "",
            "iep_is_active": "1",
            "goal_done": "true"
        }
    ],
    [
      {
        "detail_id": "48272",
        "iep_id": "259",
        "goal_id": "22424",
        "parent_id": "22423",
        "goal_type": "B",
        "service_group": "Academics",
        "service_type": "Academics : Social Skills",
        "iep_goal": "By mid-year  Valentino will maintain attention without distraction with an adult while doing an activity in math session for 3 minutes with 75% accuracy in 3 out of 4 consecutive trials with moderate (6-8) verbal and tactile cues as measured by data collection.",
        "goal_sequence": null,
        "comment_id": "7",
        "goal_comments": "Valentino has demonstrated slow and steady progress towards this benchmark. He has demonstrated an average of 65% accuracy towards the goal criteria. He is able to maintain attention with an adult for an average of 120 seconds doing a math activity with moderate support. For the upcoming quarter, Valentino will improve in his joint attention during math activities with appropriate support through (1) sensory break lasting no more than 2 mins during a session.",
        "level_of_performance": "3",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48273",
        "iep_id": "259",
        "goal_id": "22425",
        "parent_id": "22423",
        "goal_type": "B",
        "service_group": "Academics",
        "service_type": "Academics : Social Skills",
        "iep_goal": "By mid-year Valentino will maintain attention without distraction with an adult while doing an activity in a literacy session for 3 minutes with 75% accuracy in 3 out of 4 consecutive trials with moderate (6-8) verbal and tactile cues as measured by data collection.",
        "goal_sequence": null,
        "comment_id": "6",
        "goal_comments": "NI",
        "level_of_performance": "NI",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48274",
        "iep_id": "259",
        "goal_id": "22426",
        "parent_id": "22423",
        "goal_type": "B",
        "service_group": "Academics",
        "service_type": "Academics : Social Skills",
        "iep_goal": "By the end of the year Valentino will maintain attention without distraction with an adult while doing an activity in math session for 5 minutes with 75% accuracy in 3 out of 4 consecutive trials with minimal support (6-8) verbal and tactile cues as measured by data collection.",
        "goal_sequence": null,
        "comment_id": "6",
        "goal_comments": "NI",
        "level_of_performance": "NI",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48275",
        "iep_id": "259",
        "goal_id": "22427",
        "parent_id": "22423",
        "goal_type": "B",
        "service_group": "Academics",
        "service_type": "Academics : Social Skills",
        "iep_goal": "By the end of the year  Valentino will maintain attention without distraction with an adult while doing an activity in a literacy session for five minutes with 75% accuracy in 3 out of 4 consecutive trials with minimal support (1-5) verbal and tactile cues as measured by data collection.",
        "goal_sequence": null,
        "comment_id": "6",
        "goal_comments": "NI",
        "level_of_performance": "NI",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": 0,
        "iep_id": "259",
        "goal_id": "22423",
        "parent_id": "0",
        "goal_type": "G",
        "service_group": "Academics",
        "service_type": "Academics : Social Skills",
        "iep_goal": "In one year, given modeling, direct instruction, and multi-sensory teaching strategies, Valentino will maintain attention without distraction with an adult while doing an activity in math and literacy session for five minutes in 3 out of 4 consecutive trials with 75% accuracy with minimal (1-5) verbal and tactile cues as measured by data collection.",
        "goal_sequence": null,
        "comment_id": "0",
        "goal_comments": "",
        "level_of_performance": "",
        "iep_is_active": "1",
        "goal_done": "true"
      }
    ],
    [
      {
        "detail_id": "48277",
        "iep_id": "259",
        "goal_id": "22429",
        "parent_id": "22428",
        "goal_type": "B",
        "service_group": "Academics",
        "service_type": "Academics : Transition",
        "iep_goal": "By mid-year, when given grocery store items, Valentino will sort 5 items and place them in the correct category (vegetable vs. fruit) in a field of 2 with 75% accuracy in 3 out of 4 consecutive trials with moderate (6-8) prompts.",
        "goal_sequence": null,
        "comment_id": "10",
        "goal_comments": "Valentino demonstrates an average of 50% accuracy towards this objective. He is able to sort vegetables and fruits into the correct categories given moderate cues. Next quarter, Valentino will work on differentiating features of presented foods (ie. color, shape, texture, presence of seeds) by using his AAC device with moderate tactile and visual cues.",
        "level_of_performance": "3",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48278",
        "iep_id": "259",
        "goal_id": "22430",
        "parent_id": "22428",
        "goal_type": "B",
        "service_group": "Academics",
        "service_type": "Academics : Transition",
        "iep_goal": "By end of year, when given grocery store items, Valentino will sort 5 items and place them in the correct category (drink vs. food) in a field of 2 with 75% accuracy in 3 out of 4 consecutive trials with moderate (6-8) prompts.",
        "goal_sequence": null,
        "comment_id": "6",
        "goal_comments": "NI",
        "level_of_performance": "NI",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48279",
        "iep_id": "259",
        "goal_id": "22431",
        "parent_id": "22428",
        "goal_type": "B",
        "service_group": "Academics",
        "service_type": "Academics : Transition",
        "iep_goal": "By end of year, when given grocery store items, Valentino will sort 10 items and place them in the correct category (vegetable vs. fruit) in a field of 2 with 75% accuracy in 3 out of 4 consecutive trials with minimal (1-5) prompts.",
        "goal_sequence": null,
        "comment_id": "6",
        "goal_comments": "NI",
        "level_of_performance": "NI",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48280",
        "iep_id": "259",
        "goal_id": "22432",
        "parent_id": "22428",
        "goal_type": "B",
        "service_group": "Academics",
        "service_type": "Academics : Transition",
        "iep_goal": "By end of year, when given grocery store items, Valentino will sort 10 items and place them in the correct category (drink vs. food) in a field of 2 with 75% accuracy in 3 out of 4 consecutive trials with minimal (1-5) prompts.",
        "goal_sequence": null,
        "comment_id": "6",
        "goal_comments": "NI",
        "level_of_performance": "NI",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": 0,
        "iep_id": "259",
        "goal_id": "22428",
        "parent_id": "0",
        "goal_type": "G",
        "service_group": "Academics",
        "service_type": "Academics : Transition",
        "iep_goal": " In one year, given 10 items to sort by category in a field of 2 related to grocery items (Vegetable vs. Fruit/ Drink vs. Food), Valentino will sort the items and place them in the correct catagory, with 75 % accuracy in  3 out of 4 consecutive trials with minimal (1-5 tactile cues) support measured by data collection.  ",
        "goal_sequence": null,
        "comment_id": "0",
        "goal_comments": "",
        "level_of_performance": "",
        "iep_is_active": "1",
        "goal_done": "true"
      }
    ],
    [
      {
        "detail_id": "48197",
        "iep_id": "259",
        "goal_id": "19053",
        "parent_id": "19052",
        "goal_type": "B",
        "service_group": "Assistive Technology",
        "service_type": "Assistive Technology",
        "iep_goal": "During a range of motivating games on his device, Valentino will sustain his gaze for 1-3 seconds in order to activate icons/targets given moderate verbal, visual, and tactile cueing/prompting in 80% of trials.",
        "goal_sequence": null,
        "comment_id": "10",
        "goal_comments": "Valentino continues to work to visually locate the icons on the screen of his new SGD with TouchChat software and head tracking access. This supports his ability to access and activate the icons to produce expressive productions. He is reducing his processing time while also benefiting from the multimodal supports at a moderate level in order to complete this tasks in 5/10 opportunities.",
        "level_of_performance": "3",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48198",
        "iep_id": "259",
        "goal_id": "19054",
        "parent_id": "19052",
        "goal_type": "B",
        "service_group": "Assistive Technology",
        "service_type": "Assistive Technology",
        "iep_goal": "Valentino will utilize mid/high-tech AAC in order to engage in social interactions with others by greeting “hi/bye” given moderate verbal, visual, and tactile cueing/prompting in 80% of trials.",
        "goal_sequence": null,
        "comment_id": "10",
        "goal_comments": "Valentino exhibits his ability to access and activate the icon on his social greeting page which introduces him \"Hi, My name is Valentino\". He is using this as well as Hello/Goodbye as opening and closing greetings with increasing consistency. He benefits from multimodal prompts, models and cues at a moderate level to support his conversational exchanges with others.",
        "level_of_performance": "3",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48199",
        "iep_id": "259",
        "goal_id": "19055",
        "parent_id": "19052",
        "goal_type": "B",
        "service_group": "Assistive Technology",
        "service_type": "Assistive Technology",
        "iep_goal": "Valentino will utilize mid/high-tech AAC in order to request wants/needs via core vocabulary (I.e., “yes/no, “more/finished”) given moderate verbal, visual, and tactile cueing/prompting in 80% of trials.",
        "goal_sequence": null,
        "comment_id": "10",
        "goal_comments": "Valentino is supported in his pursuit of achieving this benchmark by careful attention to appropriate positioning and placement of his SGD. The procurement of a new chair for him will provide additional consideration of consistent access to his SGD throughout his day. Valentino's use of core vocabulary is progressing well with his increased familiarity with the icons and their placement on the page sets on his device.",
        "level_of_performance": "3",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48200",
        "iep_id": "259",
        "goal_id": "19056",
        "parent_id": "19052",
        "goal_type": "B",
        "service_group": "Assistive Technology",
        "service_type": "Assistive Technology",
        "iep_goal": "Valentino will trial a variety of access points to determine the most efficient method of activation to assist in participation of preferred tasks/activities.",
        "goal_sequence": null,
        "comment_id": "3",
        "goal_comments": "As per assessment and trials, it has been determined that Valentino's most efficient method of activation is via direct selection with head tracking. The opportunities to support this access will continue in his other benchmarks.",
        "level_of_performance": "Discontinue",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "0",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": 0,
        "iep_id": "259",
        "goal_id": "19052",
        "parent_id": "0",
        "goal_type": "G",
        "service_group": "Assistive Technology",
        "service_type": "Assistive Technology",
        "iep_goal": "Valentino will be able to successfully and consistently use a mid or high tech AAC device in order to participate in a variety of activities across different environments and engage in social interactions with others.",
        "goal_sequence": null,
        "comment_id": "0",
        "goal_comments": "",
        "level_of_performance": "",
        "iep_is_active": "1",
        "goal_done": "true"
      }
    ],
    [
      {
        "detail_id": "48202",
        "iep_id": "259",
        "goal_id": "19068",
        "parent_id": "19067",
        "goal_type": "B",
        "service_group": "Music Therapy",
        "service_type": "Music Therapy : Cognitive",
        "iep_goal": "Valentino will localize to the sound of presented music or his name in 3/5 trials through MSOT training with moderate support.",
        "goal_sequence": null,
        "comment_id": "15",
        "goal_comments": "Valentino has met this benchmark. This benchmark will be updated to include the added task of orienting towards music. Additionally, Valentino will work on doing so independently or with minimal assistance. New benchmark: Valentino will localize and orient towards the sound of vocal and instrumental music in 3/5 trials independently or with minimal support.",
        "level_of_performance": "4",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48203",
        "iep_id": "259",
        "goal_id": "19069",
        "parent_id": "19067",
        "goal_type": "B",
        "service_group": "Music Therapy",
        "service_type": "Music Therapy : Cognitive",
        "iep_goal": "Valentino will localize to the sound of presented music or his name in 4/5 trials through MSOT training with moderate support.",
        "goal_sequence": null,
        "comment_id": "7",
        "goal_comments": "Valentino has maintained his progress in this goal. We will continue to work on localizing to instruments, voices, and recorded music during Music Therapy Sessions next quarter. Given that Valentino typically demonstrates localization either independently or with minimal assistance during sessions, this benchmark should also be adjusted to: Valentino will localize and orient towards the sound of vocal and instrumental music in 4/5 trials independently or with minimal support. This new benchmark reflects Valentino's independence with this skill while continuing to allow us to measure his progress in this goal.",
        "level_of_performance": "3",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48204",
        "iep_id": "259",
        "goal_id": "19070",
        "parent_id": "19067",
        "goal_type": "B",
        "service_group": "Music Therapy",
        "service_type": "Music Therapy : Cognitive",
        "iep_goal": "Valentino will localize to the sound of presented music or his name in 5/5 trials through MSOT training with moderate support.",
        "goal_sequence": null,
        "comment_id": "7",
        "goal_comments": "Valentino has maintained his progress in this goal. We will continue to work on localizing to instruments, voices, and recorded music during Music Therapy Sessions next quarter. Given that Valentino typically demonstrates localization either independently or with minimal assistance during sessions, this benchmark should also be adjusted to: Valentino will localize and orient towards the sound of vocal and instrumental music in 5/5 trials independently or with minimal support. This new benchmark reflects Valentino's independence with this skill while continuing to allow us to measure his progress in this goal.",
        "level_of_performance": "3",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": 0,
        "iep_id": "259",
        "goal_id": "19067",
        "parent_id": "0",
        "goal_type": "G",
        "service_group": "Music Therapy",
        "service_type": "Music Therapy : Cognitive",
        "iep_goal": "Through Musical Sensory Orientation Training (MSOT), Valentino will increase his overall awareness of his environment within the context of Music Therapy. ",
        "goal_sequence": null,
        "comment_id": "0",
        "goal_comments": "",
        "level_of_performance": "",
        "iep_is_active": "1",
        "goal_done": "true"
      }
    ],
    [
      {
        "detail_id": "48206",
        "iep_id": "259",
        "goal_id": "19076",
        "parent_id": "19075",
        "goal_type": "B",
        "service_group": "Music Therapy",
        "service_type": "Music Therapy : Communication",
        "iep_goal": "Valentino will participate in 2/4 cycles of communication through SYCOM training with moderate support. ",
        "goal_sequence": null,
        "comment_id": "6",
        "goal_comments": "NI",
        "level_of_performance": "NI",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48207",
        "iep_id": "259",
        "goal_id": "19077",
        "parent_id": "19075",
        "goal_type": "B",
        "service_group": "Music Therapy",
        "service_type": "Music Therapy : Communication",
        "iep_goal": "Valentino will participate in 3/4 cycles of communication through SYCOM training with moderate support. ",
        "goal_sequence": null,
        "comment_id": "6",
        "goal_comments": "NI",
        "level_of_performance": "NI",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48208",
        "iep_id": "259",
        "goal_id": "19078",
        "parent_id": "19075",
        "goal_type": "B",
        "service_group": "Music Therapy",
        "service_type": "Music Therapy : Communication",
        "iep_goal": "Valentino will participate in 4/4 cycles of communication through SYCOM training with moderate support. ",
        "goal_sequence": null,
        "comment_id": "6",
        "goal_comments": "NI",
        "level_of_performance": "NI",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": 0,
        "iep_id": "259",
        "goal_id": "19075",
        "parent_id": "0",
        "goal_type": "G",
        "service_group": "Music Therapy",
        "service_type": "Music Therapy : Communication",
        "iep_goal": "Through Symbolic Communication Training (SYCOM), Valentino will increase his ability to share attention within the context of Music Therapy. ",
        "goal_sequence": null,
        "comment_id": "0",
        "goal_comments": "",
        "level_of_performance": "",
        "iep_is_active": "1",
        "goal_done": "true"
      }
    ],
    [
      {
        "detail_id": "48281",
        "iep_id": "259",
        "goal_id": "23062",
        "parent_id": "19090",
        "goal_type": "B",
        "service_group": "Music Therapy",
        "service_type": "Music Therapy : Sensorimotor",
        "iep_goal": "Valentino will engage in instrument play (e.g. tambourine, piano, drum) for 30 seconds with moderate support during TIMP exercises.",
        "goal_sequence": null,
        "comment_id": "15",
        "goal_comments": "Valentino has met this benchmark. He does an excellent job holding and playing small percussive instruments like tambourine and mini maracas. Next quarter, I would like to specifically focus on reaching towards and hitting or tapping larger instruments like hand drums, piano, and keyboard. New benchmark: Valentino will reach towards and intentionally hit or tap a presented instrument to make sound for 15 seconds with minimal or moderate support. Another (fourth) new benchmark for Valentino will be: Valentino will reach towards and intentionally hit or tap a presented instrument to make sound for 30 seconds with minimal or moderate support. Finally, to reflect the broader focus of this goal next quarter, the goal should be adjusted to: By participating in instrument playing interventions, Valentino will increase motor skills within the context of Music Therapy.",
        "level_of_performance": "4",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48282",
        "iep_id": "259",
        "goal_id": "23063",
        "parent_id": "19090",
        "goal_type": "B",
        "service_group": "Music Therapy",
        "service_type": "Music Therapy : Sensorimotor",
        "iep_goal": "Valentino will engage in instrument play (e.g. tambourine, piano, drum) for 45 seconds with moderate support during TIMP exercises.",
        "goal_sequence": null,
        "comment_id": "4",
        "goal_comments": "Valentino does an excellent job holding and playing small percussive instruments like tambourine and mini maracas for an extended time. I anticipate him meeting this benchmark.",
        "level_of_performance": "3",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48283",
        "iep_id": "259",
        "goal_id": "23064",
        "parent_id": "19090",
        "goal_type": "B",
        "service_group": "Music Therapy",
        "service_type": "Music Therapy : Sensorimotor",
        "iep_goal": "Valentino will engage in instrument play (e.g. tambourine, piano, drum) for 60 seconds with moderate support  during TIMP exercises.",
        "goal_sequence": null,
        "comment_id": "4",
        "goal_comments": "Valentino does an excellent job holding and playing small percussive instruments like tambourine and mini maracas. This benchmark remains appropriate at this time to support Valentino in building endurance for holding and shaking small instruments.",
        "level_of_performance": "2",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": 0,
        "iep_id": "259",
        "goal_id": "19090",
        "parent_id": "0",
        "goal_type": "G",
        "service_group": "Music Therapy",
        "service_type": "Music Therapy : Sensorimotor",
        "iep_goal": "By participating in Therapeutical Instrumental Music Performance (TIMP) training, Valentino will increase fine motor skills within the context of Music Therapy.  ",
        "goal_sequence": null,
        "comment_id": "0",
        "goal_comments": "",
        "level_of_performance": "",
        "iep_is_active": "1",
        "goal_done": "true"
      }
    ],
    [
      {
        "detail_id": "48213",
        "iep_id": "259",
        "goal_id": "19102",
        "parent_id": "19099",
        "goal_type": "B",
        "service_group": "Occupational Therapy",
        "service_type": "Occupational Therapy : Self Care",
        "iep_goal": "Valentino will scoop his food and bring it to his mouth during self-feeding with adaptive equipment as needed, (I.e., adapted bowl, dycem) with minimal verbal cues and physical assistance to self-feed 75% of his lunch in 3 out of 5 school days. ",
        "goal_sequence": null,
        "comment_id": "1",
        "goal_comments": "Valentino continues to require maximal assistance to use an adaptive spoon to scoop his food from his adaptive bowl  (scoop dish) and moderate assistance to bring a loaded spoon to his mouth to feed himself 75% of his lunch. He requires positioning of his wrist and hands on the spoon in order to minimize spillage.",
        "level_of_performance": "2",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48214",
        "iep_id": "259",
        "goal_id": "19104",
        "parent_id": "19099",
        "goal_type": "B",
        "service_group": "Occupational Therapy",
        "service_type": "Occupational Therapy : Self Care",
        "iep_goal": "Valentino will improve participation in hand washing by extending both arms into the sink and maintaining midline position for duration of scrubbing and rinsing given moderate physical assistance in 4/5 trials.",
        "goal_sequence": null,
        "comment_id": "7",
        "goal_comments": "Valentino demonstrates the ability to bring his hands to midline in the sink with maximal assistance in 3/5 trials. He requires maximal assistance to complete all steps of hand washing but demonstrates improved tolerance during this self care activity.",
        "level_of_performance": "2",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": 0,
        "iep_id": "259",
        "goal_id": "19099",
        "parent_id": "0",
        "goal_type": "G",
        "service_group": "Occupational Therapy",
        "service_type": "Occupational Therapy : Self Care",
        "iep_goal": "In one year of intervention, Valentino will increase participation in self-care activities as evidenced by meeting 4/4 short term objectives. ",
        "goal_sequence": null,
        "comment_id": "0",
        "goal_comments": "",
        "level_of_performance": "",
        "iep_is_active": "1",
        "goal_done": "true"
      }
    ],
    [
      {
        "detail_id": "48216",
        "iep_id": "259",
        "goal_id": "19112",
        "parent_id": "19111",
        "goal_type": "B",
        "service_group": "Occupational Therapy",
        "service_type": "Occupational Therapy: Academics",
        "iep_goal": "Valentino will improve bilateral hand coordination skills by using his right hand as a functional assist during classroom activities (i.e. stabilize a book, stabilize paper, etc.) by initiating and maintaining use of his right hand in no less than 50% of opportunities given minimal physical assistance and moderate verbal cues.   ",
        "goal_sequence": null,
        "comment_id": "7",
        "goal_comments": "Valentino demonstrates the ability to use his right hand to assist in holding objects such as books, slant board, balls, and containers with maximal assistance to initiate grasp on these objects in 30% of opportunities. He is able to maintain grasp for 5-10 seconds once placed in his hand but requires moderate repositioning and tactile cues for proper wrist and finger placement.",
        "level_of_performance": "2",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48217",
        "iep_id": "259",
        "goal_id": "19113",
        "parent_id": "19111",
        "goal_type": "B",
        "service_group": "Occupational Therapy",
        "service_type": "Occupational Therapy: Academics",
        "iep_goal": "Valentino will increase pre-handwriting skills by maintaining a grasp on an art tool (i.e., marker, paintbrush) utilizing adaptive equipment as needed (I.e., built-up handle, slant board) to produce vertical and horizontal lines with moderate verbal/visual/tactile cues in 3 out of 4 trials. ",
        "goal_sequence": null,
        "comment_id": "7",
        "goal_comments": "Valentino currently utilizes a palmar grasp on writing utensils. He is able to maintain grasp on markers when placed in his hand but requires maximal hand over hand assist to purposefully bring the marker to the paper and make lines in 3 out of 4 trials. Valentino requires the use of a slant board to promote wrist extension during pre-writing activities.",
        "level_of_performance": "2",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48218",
        "iep_id": "259",
        "goal_id": "19114",
        "parent_id": "19111",
        "goal_type": "B",
        "service_group": "Occupational Therapy",
        "service_type": "Occupational Therapy: Academics",
        "iep_goal": "Valentino will improve functional endurance during seated academic tasks as demonstrated by remaining in an upright, seated position on a bench or on a mat for 10 minutes with no more than moderate verbal/tactile cues in 4 out of 5 trials. ",
        "goal_sequence": null,
        "comment_id": "7",
        "goal_comments": "Valentino has continued to make good progress in his overall core strength and trunk control to sit upright on various surfaces (bench, stationary chair, mat table) for 10 minutes in 3 out of 5 trials with contact guard assistance to maintain an upright position and minimal assistance to maintain alignment.",
        "level_of_performance": "2",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": 0,
        "iep_id": "259",
        "goal_id": "19111",
        "parent_id": "0",
        "goal_type": "G",
        "service_group": "Occupational Therapy",
        "service_type": "Occupational Therapy: Academics",
        "iep_goal": "In one year of intervention, Valentino will increase participation in academic activities as evidenced by meeting 3/3 short term objectives.        ",
        "goal_sequence": null,
        "comment_id": "0",
        "goal_comments": "",
        "level_of_performance": "",
        "iep_is_active": "1",
        "goal_done": "true"
      }
    ],
    [
      {
        "detail_id": "48220",
        "iep_id": "259",
        "goal_id": "19116",
        "parent_id": "19115",
        "goal_type": "B",
        "service_group": "Occupational Therapy",
        "service_type": "Occupational Therapy: Play",
        "iep_goal": "Valentino will increase participation in community outings by placing 5 grocery items into a designated area with moderate verbal/tactile/visual cues, in 3 out of 4 trials.   ",
        "goal_sequence": null,
        "comment_id": "7",
        "goal_comments": "Valentino continues to work on preparatory activities to address this goal, working on grasp and functional release of objects. Valentino is able to maintain grasp on an object once placed in his hand but requires maximal assistance and tactile cues to release objects in 3 out of 4 trials.",
        "level_of_performance": "2",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48221",
        "iep_id": "259",
        "goal_id": "19117",
        "parent_id": "19115",
        "goal_type": "B",
        "service_group": "Occupational Therapy",
        "service_type": "Occupational Therapy: Play",
        "iep_goal": "Valentino will improve bilateral coordination skills as evidenced by using both hands to stabilize a ball and push it to a peer with moderate verbal cues and physical assistance to incorporate his right hand in 3 out of 5 trials. ",
        "goal_sequence": null,
        "comment_id": "7",
        "goal_comments": "Valentino requires moderate hand over hand assistance to use both hands to hold onto a ball in 2 out of 5 trials. He requires maximal assistance to push both arms forward at the same time. Valentino will continue to work on activities involving use of both hands together to address this goal.",
        "level_of_performance": "2",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": 0,
        "iep_id": "259",
        "goal_id": "19115",
        "parent_id": "0",
        "goal_type": "G",
        "service_group": "Occupational Therapy",
        "service_type": "Occupational Therapy: Play",
        "iep_goal": "In one year of intervention, Valentino will increase participation in social and community activities as evidenced by meeting 2/2 short term objectives.      ",
        "goal_sequence": null,
        "comment_id": "0",
        "goal_comments": "",
        "level_of_performance": "",
        "iep_is_active": "1",
        "goal_done": "true"
      }
    ],
    [
      {
        "detail_id": "48227",
        "iep_id": "259",
        "goal_id": "19128",
        "parent_id": "19127",
        "goal_type": "B",
        "service_group": "Physical Therapy",
        "service_type": "Physical Therapy",
        "iep_goal": "Valentino will be able to perform step up and down with moderate assistance, 10 repetitions on each side using 2-inch-high step stool,4/5 trials.",
        "goal_sequence": null,
        "comment_id": "3",
        "goal_comments": "The goal was very generalized depending on Valentino's capabilities, hence a more specific goal/benchmark is set for the quarter that will enable Valentino to progress in all aspects of his life at school and home. Those goals will target the specific muscles required to achieve these goals.",
        "level_of_performance": "Discontinue",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "0",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48230",
        "iep_id": "259",
        "goal_id": "19131",
        "parent_id": "19127",
        "goal_type": "B",
        "service_group": "Physical Therapy",
        "service_type": "Physical Therapy",
        "iep_goal": "Valentino will be able to walk 250 feet with two hand-held assists with 1 break  in 4/5 trials",
        "goal_sequence": null,
        "comment_id": "3",
        "goal_comments": "The goal was very generalized depending on Valentino's capabilities, hence a more specific goal/benchmark is set for the quarter that will enable Valentino to progress in all aspects of his life at school and home. Those goals will target the specific muscles required to achieve these goals.",
        "level_of_performance": "Discontinue",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "0",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48231",
        "iep_id": "259",
        "goal_id": "19132",
        "parent_id": "19127",
        "goal_type": "B",
        "service_group": "Physical Therapy",
        "service_type": "Physical Therapy",
        "iep_goal": "Valentino will be able to walk 350 feet with two hand-held assists with 1 break  in 4/5 trials",
        "goal_sequence": null,
        "comment_id": "3",
        "goal_comments": "The goal was very generalized depending on Valentino's capabilities, hence a more specific goal/benchmark is set for the quarter that will enable Valentino to progress in all aspects of his life at school and home. Those goals will target the specific muscles required to achieve these goals.",
        "level_of_performance": "Discontinue",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "0",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": 0,
        "iep_id": "259",
        "goal_id": "19127",
        "parent_id": "0",
        "goal_type": "G",
        "service_group": "Physical Therapy",
        "service_type": "Physical Therapy",
        "iep_goal": "In one year, Valentino will walk 150 feet with minimal verbal cueing in the least resistive device in 4/5 trials to be more independent while transitioning around the school with his peers to participate in school and classroom activities ",
        "goal_sequence": null,
        "comment_id": "0",
        "goal_comments": "",
        "level_of_performance": "",
        "iep_is_active": "0",
        "goal_done": "true"
      }
    ],
    [
      {
        "detail_id": "48286",
        "iep_id": "259",
        "goal_id": "23713",
        "parent_id": "23712",
        "goal_type": "B",
        "service_group": "Physical Therapy",
        "service_type": "Physical Therapy",
        "iep_goal": "Valentino will be able to take 50 backward steps with moderate assistance in a fully supported gait trainer in 3/4 trials to increase pelvic mobility ",
        "goal_sequence": null,
        "comment_id": "10",
        "goal_comments": "Valentino currently manages to take 7 small steps backward with maximal verbal and tactile cueing while using a fully supported gait trainer in 1/4 trials. He is currently working on motor planning, pelvic mobility, and muscle strengthening.",
        "level_of_performance": "2",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48287",
        "iep_id": "259",
        "goal_id": "23714",
        "parent_id": "23712",
        "goal_type": "B",
        "service_group": "Physical Therapy",
        "service_type": "Physical Therapy",
        "iep_goal": "Valentino will be able to ambulate for approximately 200 feet indoors and in the community with bilateral handheld assistance in 3/4 trials. ",
        "goal_sequence": null,
        "comment_id": "10",
        "goal_comments": "Valentino can walk up to 150 feet with bilateral handheld assistance in 3/4 trials but requires additional assistance for weight shift and tactile cueing with two breaks. On a good day, Valentino walks with one or no breaks but on some days he requires maximal verbal and tactile cueing along with more than two breaks. Currently, Valentino is working on endurance training like standing for more than 15 mins, biking and on motor planning.",
        "level_of_performance": "3",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48288",
        "iep_id": "259",
        "goal_id": "23715",
        "parent_id": "23712",
        "goal_type": "B",
        "service_group": "Physical Therapy",
        "service_type": "Physical Therapy",
        "iep_goal": "Valentino will be able to ambulate for approximately 300 feet indoors and in the community with bilateral handheld assistance in 3/4 trials. ",
        "goal_sequence": null,
        "comment_id": "2",
        "goal_comments": "Valentino can walk up to 150 feet with bilateral handheld assistance in 3/4 trials but requires additional assistance for weight shift and tactile cueing with two breaks. On a good day, Valentino walks with one or no breaks but on some days he requires maximal verbal and tactile cueing along with more than two breaks. Currently, Valentino is working on endurance training like standing for more than 15 mins, biking and on motor planning.",
        "level_of_performance": "3",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48289",
        "iep_id": "259",
        "goal_id": "23716",
        "parent_id": "23712",
        "goal_type": "B",
        "service_group": "Physical Therapy",
        "service_type": "Physical Therapy",
        "iep_goal": "Valentino will be able to ambulate for approximately 400 feet indoors and in the community with bilateral handheld assistance in 3/4 trials. ",
        "goal_sequence": null,
        "comment_id": "2",
        "goal_comments": "Valentino can walk up to 150 feet with bilateral handheld assistance in 3/4 trials but requires additional assistance for weight shift and tactile cueing with two breaks. On a good day, Valentino walks with one or no breaks but on some days he requires maximal verbal and tactile cueing along with more than two breaks. Currently, Valentino is working on endurance training like standing for more than 15 mins, biking and on motor planning.",
        "level_of_performance": "1",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": 0,
        "iep_id": "259",
        "goal_id": "23712",
        "parent_id": "0",
        "goal_type": "G",
        "service_group": "Physical Therapy",
        "service_type": "Physical Therapy",
        "iep_goal": " In one year, Valentino will be able to ambulate for approximately 400 feet indoors and in the community with bilateral handheld assistance in 3/4 trials.",
        "goal_sequence": null,
        "comment_id": "0",
        "goal_comments": "",
        "level_of_performance": "",
        "iep_is_active": "1",
        "goal_done": "true"
      }
    ],
    [
      {
        "detail_id": "48291",
        "iep_id": "259",
        "goal_id": "23718",
        "parent_id": "23717",
        "goal_type": "B",
        "service_group": "Physical Therapy",
        "service_type": "Physical Therapy",
        "iep_goal": "     Valentino will be able to ascend and descend 10 stairs with maximal assistance at the upper extremities to participate in ADLs effectively in 4/5 trials. ",
        "goal_sequence": null,
        "comment_id": "10",
        "goal_comments": "Currently, Valentino can ascend and descend 10 stairs with moderate assistance at the pelvis for weight shifts along with maximal assistance at the upper extremity to hold the railings to pull himself up while ascending the stairs and help with knee unlocking while descending the stairs. He is working on motor planning, and pelvic mobility with activities like sit to stands and half-kneeling to achieve his goal.",
        "level_of_performance": "3",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48292",
        "iep_id": "259",
        "goal_id": "23719",
        "parent_id": "23717",
        "goal_type": "B",
        "service_group": "Physical Therapy",
        "service_type": "Physical Therapy",
        "iep_goal": "Valentino will be able to ascend and descend 10 stairs with moderate assistance at the upper extremities to participate in ADLs effectively in 4/5 trials. ",
        "goal_sequence": null,
        "comment_id": "10",
        "goal_comments": "Currently, Valentino can ascend and descend 10 stairs with moderate assistance at the pelvis for weight shifts along with maximal assistance at the upper extremity to hold the railings to pull himself up while ascending the stairs and help with knee unlocking while descending the stairs. He is working on motor planning, and pelvic mobility with activities like sit to stands and half-kneeling to achieve his goal.",
        "level_of_performance": "2",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48293",
        "iep_id": "259",
        "goal_id": "23720",
        "parent_id": "23717",
        "goal_type": "B",
        "service_group": "Physical Therapy",
        "service_type": "Physical Therapy",
        "iep_goal": "Valentino will be able to ascend and descend 1 flight of stairs with minimal assistance at the upper extremities to participate in ADLs effectively in 4/5 trials. ",
        "goal_sequence": null,
        "comment_id": "6",
        "goal_comments": "NI",
        "level_of_performance": "NI",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": 0,
        "iep_id": "259",
        "goal_id": "23717",
        "parent_id": "0",
        "goal_type": "G",
        "service_group": "Physical Therapy",
        "service_type": "Physical Therapy",
        "iep_goal": "In one academic year, Valentino will be able to ascend and descend 1 flight of stairs with minimal assistance at the upper extremities to participate in ADLs effectively in 4/5 trials. ",
        "goal_sequence": null,
        "comment_id": "0",
        "goal_comments": "",
        "level_of_performance": "",
        "iep_is_active": "1",
        "goal_done": "true"
      }
    ],
    [
      {
        "detail_id": "48233",
        "iep_id": "259",
        "goal_id": "19138",
        "parent_id": "19137",
        "goal_type": "B",
        "service_group": "Speech-Language Therapy",
        "service_type": "Speech-Language Therapy : Expressive",
        "iep_goal": "Valentino will activate his device to choose the appropriate word from a field of 2 to initiate or terminate an activity via partner assisted scanning (e.g., two single voice-output switches) and/or utilizing a high-tech AAC device given repetition, processing time, and moderate support of verbal, visual, and tactile cues for 80% of trials.",
        "goal_sequence": null,
        "comment_id": "11",
        "goal_comments": "Student has demonstrated fast steady progress toward goal. Valentino now works on this goal through utilizing a personal Speech Generating Device (SGD) with Touchchat software array of 2 icons with access point via headtracking. He benefits from moderate to maximal verbal and tactile cues with accuracy ranging from 60% - 75% of trials. The level of accuracy can vary session to session and is suspected to be reliant upon motivation or interest in activity. Best performance is observed when Valentino performs at minimal cueing level, with only one verbal prompt required to activate his device. This goal will be continued in the upcoming quarter to ensure consistency and reduce level of support needed.",
        "level_of_performance": "3",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48234",
        "iep_id": "259",
        "goal_id": "19139",
        "parent_id": "19137",
        "goal_type": "B",
        "service_group": "Speech-Language Therapy",
        "service_type": "Speech-Language Therapy : Expressive",
        "iep_goal": "Valentino will activate his device to choose the appropriate word from a field of 2 to make an appropriate request/comment during an activity via partner assisted scanning (e.g., two single voice-output switches) and/or utilizing a high-tech AAC device given repetition, processing time, and moderate support of verbal, visual, and tactile cues for 80% of trials.",
        "goal_sequence": null,
        "comment_id": "10",
        "goal_comments": "Student has demonstrated steady progress toward goal. Valentino now works on this goal through utilizing a personal Speech Generating Device (SGD) with Touchchat software array of 2 icons with access point via headtracking. He benefits from moderate to maximal verbal and tactile cues with accuracy ranging from 55% - 70% of trials. The level of accuracy can vary session to session and is suspected to be reliant upon motivation or interest in activity. Best performance is observed when Valentino performs at minimal cueing level, with only one verbal prompt required to activate his device. This goal will be continued in the upcoming quarter to ensure consistency and reduce level of support needed.",
        "level_of_performance": "3",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48235",
        "iep_id": "259",
        "goal_id": "19140",
        "parent_id": "19137",
        "goal_type": "B",
        "service_group": "Speech-Language Therapy",
        "service_type": "Speech-Language Therapy : Expressive",
        "iep_goal": "Valentino will activate his device to choose the appropriate word from a field of 2 to greet a familiar peer or adult via partner assisted scanning (e.g., two single voice-output switches) and/or utilizing a high-tech AAC device given repetition, processing time, and moderate support of verbal, visual, and tactile cues for 80% of trials. ",
        "goal_sequence": null,
        "comment_id": "11",
        "goal_comments": "Student has demonstrated fast steady progress toward goal. Valentino now works on this goal through utilizing a personal Speech Generating Device (SGD) with Touchchat software array of 2 icons with access point via headtracking to participate in greetings. He benefits from moderate to maximal verbal and tactile cues with accuracy ranging from 65% - 75% of trials. The level of accuracy can vary session to session and is suspected to be reliant upon motivation or interest in activity. Best performance is observed when Valentino performs at minimal cueing level, with only one verbal prompt required to activate his device. This goal will be continued in the upcoming quarter to ensure consistency and reduce level of support needed.",
        "level_of_performance": "3",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": 0,
        "iep_id": "259",
        "goal_id": "19137",
        "parent_id": "0",
        "goal_type": "G",
        "service_group": "Speech-Language Therapy",
        "service_type": "Speech-Language Therapy : Expressive",
        "iep_goal": "Valentino will increase his expressive language skills by using total communication (I.e., verbal approximations, facial expressions, gestures, low and high-tech AAC devices) in order to initiate/terminate an activity, make appropriate requests, and greet familiar peers and adults across all contexts given support of aided language stimulation (e.g., modeling) and moderate support of verbal, visual, and tactile cues. ",
        "goal_sequence": null,
        "comment_id": "0",
        "goal_comments": "",
        "level_of_performance": "",
        "iep_is_active": "1",
        "goal_done": "true"
      }
    ],
    [
      {
        "detail_id": "48242",
        "iep_id": "259",
        "goal_id": "19147",
        "parent_id": "19146",
        "goal_type": "B",
        "service_group": "Speech-Language Therapy",
        "service_type": "Speech-Language Therapy : Pragmatics",
        "iep_goal": "Valentino will demonstrate joint attention with a familiar partner or peer when participating in a structured activity by maintaining focus on the target object with 80% accuracy given the support of aided language stimulation (e.g., modeling) and moderate verbal, visual cues, and tactile cues. ",
        "goal_sequence": null,
        "comment_id": "3",
        "goal_comments": "Goal has been adjusted to be functional and achievable for Valentino. Proposed new goal: \"Valentino will activate his device from a field of 2 to express how he is feeling during times of high emotion (i.e. overly excited/upset) with 80% accuracy given repetition, processing time, and moderate support of verbal, visual, and tactile cues.\"",
        "level_of_performance": "Discontinue",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "0",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48243",
        "iep_id": "259",
        "goal_id": "19148",
        "parent_id": "19146",
        "goal_type": "B",
        "service_group": "Speech-Language Therapy",
        "service_type": "Speech-Language Therapy : Pragmatics",
        "iep_goal": "Valentino will initiate conversation (i.e., greetings, social exchanges) via switch activation or high-tech AAC device when provided with aided language stimulation and moderate multimodal cueing in 4/5 trials during structured activities.",
        "goal_sequence": null,
        "comment_id": "11",
        "goal_comments": "Student has demonstrated fast steady progress toward goal. Valentino now works on this goal through utilizing a personal Speech Generating Device (SGD) with Touchchat software array of 2 icons with access point via headtracking to participate in greetings. He benefits from moderate to maximal verbal and tactile cues with accuracy ranging from 65% - 75% of trials. The level of accuracy can vary session to session and is suspected to be reliant upon motivation or interest in activity. Best performance is observed when Valentino performs at minimal cueing level, with only one verbal prompt required to activate his device. This goal will be continued in the upcoming quarter to ensure consistency and reduce level of support needed.",
        "level_of_performance": "3",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48244",
        "iep_id": "259",
        "goal_id": "19149",
        "parent_id": "19146",
        "goal_type": "B",
        "service_group": "Speech-Language Therapy",
        "service_type": "Speech-Language Therapy : Pragmatics",
        "iep_goal": "Valentino will comment appropriately (e.g., good, I like it, my turn) during a structured activity via switch activation or high-tech AAC device given aided language stimulation (e.g., modeling), processing time, and moderate support of verbal, visual, and tactile cues for 80% of trials.",
        "goal_sequence": null,
        "comment_id": "11",
        "goal_comments": "Student has demonstrated slow steady progress toward goal. Valentino now works on this goal through utilizing a personal Speech Generating Device (SGD) with Touchchat software array of 2 icons with access point via headtracking to make an appropriate comment. He benefits from moderate to maximal verbal and tactile cues with accuracy ranging from 55% - 70% of trials. The level of accuracy can vary session to session and is suspected to be reliant upon motivation or interest in activity. Best performance is observed when Valentino performs at minimal cueing level, with only one verbal prompt required to activate his device. This goal will be continued in the upcoming quarter to ensure consistency and reduce level of support needed.",
        "level_of_performance": "3",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": 0,
        "iep_id": "259",
        "goal_id": "19146",
        "parent_id": "0",
        "goal_type": "G",
        "service_group": "Speech-Language Therapy",
        "service_type": "Speech-Language Therapy : Pragmatics",
        "iep_goal": "Valentino will improve his overall pragmatic language skills using total communication (I.e., verbal approximations, facial expressions, gestures, low and high-tech AAC devices) in order to demonstrate joint attention, initiate conversation, and make appropriate comments across all contexts given support of aided language stimulation (e.g., modeling) and moderate support of verbal, visual, and tactile cues. ",
        "goal_sequence": null,
        "comment_id": "0",
        "goal_comments": "",
        "level_of_performance": "",
        "iep_is_active": "1",
        "goal_done": "true"
      }
    ],
    [
      {
        "detail_id": "48246",
        "iep_id": "259",
        "goal_id": "19151",
        "parent_id": "19150",
        "goal_type": "B",
        "service_group": "Speech-Language Therapy",
        "service_type": "Speech-Language Therapy : Receptive",
        "iep_goal": "Valentino will discriminate between two picture symbols (with coinciding orthographic descriptors) via eye gaze given repetition, processing time, and moderate support of verbal, visual, and tactile cues for 80% of trials. ",
        "goal_sequence": null,
        "comment_id": "10",
        "goal_comments": "Student has demonstrated slow steady progress toward goal. Valentino now works on this goal through utilizing a personal Speech Generating Device (SGD) with Touchchat to choose an appropriate word from a field of two after looking and being presented with two images paired with core words or tangible objects. He benefits from moderate to maximal verbal, visual, tactile cues with accuracy ranging from 40% - 50% of trials. The level of accuracy can vary session to session and is suspected to be reliant upon motivation or interest in activity. Best performance is observed when Valentino performs at minimal cueing level, with only one verbal prompt required. This goal will be continued in the upcoming quarter to ensure consistency and reduce level of support needed.",
        "level_of_performance": "3",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48249",
        "iep_id": "259",
        "goal_id": "19154",
        "parent_id": "19150",
        "goal_type": "B",
        "service_group": "Speech-Language Therapy",
        "service_type": "Speech-Language Therapy : Receptive",
        "iep_goal": "Valentino will receptively identify familiar objects/people as demonstrated by his ability to select the appropriate object via partner assisted scanning (e.g., two single voice-output switches) and/or utilizing a high-tech AAC device given repetition, processing time, and moderate support of verbal, visual, and tactile cues for 80% of trials. ",
        "goal_sequence": null,
        "comment_id": "10",
        "goal_comments": "Newly introduced goal. Valentino works on this goal through utilizing a personal Speech Generating Device (SGD) with Touchchat to choose an appropriate word from a field of two after looking and being presented with two images of familiar objects/people paired with core words/names. He benefits from moderate to maximal verbal, visual, tactile cues with accuracy ranging from 30% - 40% of trials. Best performance is observed when Valentino performs at minimal cueing level, with only one verbal prompt required. This goal will be continued in the upcoming quarter to ensure consistency and reduce level of support.",
        "level_of_performance": "1",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": 0,
        "iep_id": "259",
        "goal_id": "19150",
        "parent_id": "0",
        "goal_type": "G",
        "service_group": "Speech-Language Therapy",
        "service_type": "Speech-Language Therapy : Receptive",
        "iep_goal": "Valentino will increase his receptive language skills by using total communication (I.e., verbal approximations, facial expressions, gestures, low and high-tech AAC devices) in order to discriminate between core words, respond to basic wh questions, and receptively identify objects/people given support of aided language stimulation (e.g., modeling) and moderate support of verbal, visual, and tactile cues.",
        "goal_sequence": null,
        "comment_id": "0",
        "goal_comments": "",
        "level_of_performance": "",
        "iep_is_active": "1",
        "goal_done": "true"
      }
    ],
    [
      {
        "detail_id": "48256",
        "iep_id": "259",
        "goal_id": "19170",
        "parent_id": "19169",
        "goal_type": "B",
        "service_group": "Vision",
        "service_type": "Vision",
        "iep_goal": "Valentino will show visual fixations on familiar objects and objects that are visually similar to familiar objects in a light and sound-controlled environment.",
        "goal_sequence": null,
        "comment_id": "11",
        "goal_comments": "Prior to receiving his glasses Valentino did not show any consistent visual fixations on objects that visually similar to familiar objects in a light and sound controlled environment. He showed visual fixation to materials that were textured based where he could access them using his visually guided reach. Being able to access the materials through touch increased Valentino's visual curiosity. When he received his glasses, he has begun to consistently fixate on familiar objects that are illuminated and or have an auditory component to them in about 3 out of 5 trials. In addition, his need to touch the materials to increase his visual curiosity was reduced. With more trials/sessions Valentino will master this benchmark.",
        "level_of_performance": "3",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": 0,
        "iep_id": "259",
        "goal_id": "19169",
        "parent_id": "0",
        "goal_type": "G",
        "service_group": "Vision",
        "service_type": "Vision",
        "iep_goal": "Valentino will show visual curiosity in most new environments when presented with novel objects, materials, and activities.",
        "goal_sequence": null,
        "comment_id": "0",
        "goal_comments": "",
        "level_of_performance": "",
        "iep_is_active": "1",
        "goal_done": "true"
      }
    ],
    [
      {
        "detail_id": "48261",
        "iep_id": "259",
        "goal_id": "19186",
        "parent_id": "19184",
        "goal_type": "B",
        "service_group": "Vision",
        "service_type": "Vision",
        "iep_goal": "Valentino will track an accommodated object with sound vertically in 4 out of 5 attempts.",
        "goal_sequence": null,
        "comment_id": "3",
        "goal_comments": "Will continue to use this Benchmark due to Valentino not mastering tracking vertically. Valentino has shown growth in his visually attentiveness and localizing visually accommodated materials in his central visual field at a rate of 4/5 trials. His next step will be to track the object as it moves vertically. He has shown the ability to track the visuals vertically when auditory inputs. Moving forward we will continue to introduce this goal with audio help strengthen his ability to track and move to tracking without sound.",
        "level_of_performance": "1",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48262",
        "iep_id": "259",
        "goal_id": "19187",
        "parent_id": "19184",
        "goal_type": "B",
        "service_group": "Vision",
        "service_type": "Vision",
        "iep_goal": "Valentino will track a metallic, illuminated or brightly colored object with spotlighting horizontally in 4 out of 5 attempts.",
        "goal_sequence": null,
        "comment_id": "1",
        "goal_comments": "Valentino has shown an increased ability to track horizontally when starting from left to right. He is able to track up until he reaches his midline and requires extended wait time, verbal prompting, material movement and auditory inputs to cross his midline into his right visual field at a rate of 5/5 attempts. I have been presenting preferred materials to Valentino in his right visual quadrant to help build visual curiosity and attentiveness in his right quadrant.Benchmark will be adjusted to include the pause at midline as we continue to address this goal.",
        "level_of_performance": "3",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": "48263",
        "iep_id": "259",
        "goal_id": "19188",
        "parent_id": "19184",
        "goal_type": "B",
        "service_group": "Vision",
        "service_type": "Vision",
        "iep_goal": "Valentino will track a metallic, illuminated or brightly colored object with spotlighting vertically in 4 out of 5 attempts.",
        "goal_sequence": null,
        "comment_id": "6",
        "goal_comments": "NI",
        "level_of_performance": "NI",
        "goal_done": "true",
        "is_active": 1,
        "iep_is_active": "1",
        "detail_mod_by": null,
        "detail_mod_date": null
      },
      {
        "detail_id": 0,
        "iep_id": "259",
        "goal_id": "19184",
        "parent_id": "0",
        "goal_type": "G",
        "service_group": "Vision",
        "service_type": "Vision",
        "iep_goal": "Valentino will visually track an accommodated object. ",
        "goal_sequence": null,
        "comment_id": "0",
        "goal_comments": "",
        "level_of_performance": "",
        "iep_is_active": "1",
        "goal_done": "true"
      }
    ]
  ]